name = "deepclaude"
main = "app/main.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-02-19"

[vars]
ALLOW_API_KEY = ""


ALLOW_ORIGINS = ""



DEEPSEEK_API_KEY = ""
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions #siliconflow, https://api.siliconflow.cn/v1/chat/completions"
DEEPSEEK_MODEL = "deepseek-reasoner"


IS_ORIGIN_REASONING = true

CLAUDE_API_KEY = ""


CLAUDE_MODEL = "claude-3-5-sonnet-20241022"


CLAUDE_PROVIDER = "anthropic"


CLAUDE_API_URL = "https://api.anthropic.com/v1/messages"


LOG_LEVEL = "INFO"
